version: '3.8'
services:
  dev:
    build: 
      context: .
    command: solara run app.py --host=0.0.0.0 --port=8082 --dev
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    ports:
      - 8082:8082